import type {
  Artifact,
  Product,
  RightsEnvelope,
  RouteDiscovery,
  SeparateWorkstream,
  SourceFreshnessSla,
  SourceRecord,
  StreamDefinition,
} from "./types.js";

const SEEDED_CATALOG_VERIFIED = "seeded_static_research_2026-05-08";

function freshnessSla(cadence: SourceFreshnessSla["cadence"], ttlSeconds: number, expectedRefresh: string, caveats: string[]): SourceFreshnessSla {
  return {
    cadence,
    ttlSeconds,
    lastVerified: SEEDED_CATALOG_VERIFIED,
    expectedRefresh,
    caveats,
  };
}

const publicOfficialRights: RightsEnvelope = {
  licenseId: "public_official_derived_facts",
  allowedUses: ["read", "summarize", "fact_extract", "cite", "private_cache", "derived_analysis"],
  prohibitedUses: ["resell_raw_source", "claim_official_endorsement", "train_without_license", "remove_attribution"],
  cacheTtlSeconds: 86_400,
  maxExtract: "facts, metadata, links, and short attributed excerpts only",
  attribution: "Source links, retrieval timestamps, and agency/source names required.",
  privacyClass: "public",
  redistribution: "derived_facts_with_citation",
};

const publicAggregateRights: RightsEnvelope = {
  ...publicOfficialRights,
  licenseId: "public_aggregate_derived_facts",
  privacyClass: "public_aggregate",
  cacheTtlSeconds: 604_800,
};

const publicDocsRights: RightsEnvelope = {
  licenseId: "public_docs_with_source_terms",
  allowedUses: ["read", "summarize", "fact_extract", "cite", "private_cache", "diff_metadata"],
  prohibitedUses: ["resell_raw_docs", "train_without_license", "claim_vendor_certification", "bypass_auth_or_paywall"],
  cacheTtlSeconds: 86_400,
  maxExtract: "facts, changelog metadata, endpoint names, and short attributed excerpts only",
  attribution: "Vendor documentation and repository links required.",
  privacyClass: "public",
  redistribution: "derived_facts_with_citation",
};

const licensedApiRights: RightsEnvelope = {
  licenseId: "licensed_api_required_before_resale",
  allowedUses: ["metadata_only_until_license_review", "private_cache_if_terms_allow"],
  prohibitedUses: ["redistribute_raw_source", "bypass_rate_limits", "evade_api_terms", "train_without_license"],
  cacheTtlSeconds: 3_600,
  maxExtract: "metadata and derived analysis only until terms are approved",
  attribution: "Provider attribution and terms review required.",
  privacyClass: "source_terms_dependent",
  redistribution: "blocked_until_license_review",
};

export const sources: SourceRecord[] = [
  {
    sourceId: "sam_gov_opportunities",
    name: "SAM.gov Contract Opportunities",
    owner: "U.S. General Services Administration",
    url: "https://sam.gov/content/opportunities",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for contract opportunity metadata, amendments, deadlines, agency names, NAICS/PSC, and source links.",
  },
  {
    sourceId: "grants_gov",
    name: "Grants.gov",
    owner: "U.S. Department of Health and Human Services",
    url: "https://www.grants.gov/",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for grant opportunity metadata, eligibility, deadlines, award ranges, and application package links.",
  },
  {
    sourceId: "regulations_gov",
    name: "Regulations.gov",
    owner: "U.S. eRulemaking Program",
    url: "https://www.regulations.gov/developers",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for docket metadata, comment windows, effective dates, and non-legal deadline watches.",
  },
  {
    sourceId: "data_gov_catalog",
    name: "Data.gov Catalog",
    owner: "U.S. General Services Administration",
    url: "https://catalog.data.gov/",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use as a discovery index for official public datasets and source-of-truth links.",
  },
  {
    sourceId: "census_acs",
    name: "U.S. Census ACS and Business Patterns",
    owner: "U.S. Census Bureau",
    url: "https://www.census.gov/data/developers.html",
    accessPattern: "official_api",
    cadence: "annual",
    risk: "green",
    rights: publicAggregateRights,
    notes: "Use for regional demographics, business-density context, and WUI/community exposure normalization.",
  },
  {
    sourceId: "fred_alfred",
    name: "FRED and ALFRED",
    owner: "Federal Reserve Bank of St. Louis",
    url: "https://fred.stlouisfed.org/docs/api/fred/",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for macro series and revision-aware evidence packs. Some API access requires a key.",
  },
  {
    sourceId: "cftc_cot",
    name: "CFTC Commitments of Traders",
    owner: "U.S. Commodity Futures Trading Commission",
    url: "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm",
    accessPattern: "official_download",
    cadence: "weekly",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for positioning context in non-advisory market-regime evidence packs.",
  },
  {
    sourceId: "sec_edgar",
    name: "SEC EDGAR APIs",
    owner: "U.S. Securities and Exchange Commission",
    url: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
    accessPattern: "official_api",
    cadence: "event_driven",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for public filings metadata, company facts, risk-factor diffs, and filing-change detection.",
  },
  {
    sourceId: "defillama",
    name: "DefiLlama",
    owner: "DefiLlama contributors",
    url: "https://defillama.com/docs/api",
    accessPattern: "open_data",
    cadence: "daily",
    risk: "yellow",
    rights: licensedApiRights,
    notes: "Treat as terms-reviewed open/partner data before redistribution; use derived market-structure analysis.",
  },
  {
    sourceId: "coingecko",
    name: "CoinGecko API",
    owner: "CoinGecko",
    url: "https://docs.coingecko.com/",
    accessPattern: "partner_api",
    cadence: "realtime",
    risk: "yellow",
    rights: licensedApiRights,
    notes: "Use only according to API plan and redistribution terms. Good signal for x402 pay-per-use market data.",
  },
  {
    sourceId: "gdelt_2",
    name: "GDELT 2.0",
    owner: "GDELT Project",
    url: "https://www.gdeltproject.org/",
    accessPattern: "open_data",
    cadence: "realtime",
    risk: "yellow",
    rights: licensedApiRights,
    notes: "Use metadata and derived event/narrative analysis; review source-level content rights before quoting.",
  },
  {
    sourceId: "cisa_kev",
    name: "CISA Known Exploited Vulnerabilities",
    owner: "Cybersecurity and Infrastructure Security Agency",
    url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
    accessPattern: "official_download",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for defensive vulnerability prioritization and proof packets.",
  },
  {
    sourceId: "nvd_cve",
    name: "NVD CVE API 2.0",
    owner: "National Institute of Standards and Technology",
    url: "https://nvd.nist.gov/developers/vulnerabilities",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for CVE metadata, CVSS, CPE context, and KEV flags.",
  },
  {
    sourceId: "first_epss",
    name: "FIRST EPSS",
    owner: "Forum of Incident Response and Security Teams",
    url: "https://api.first.org/epss/",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for exploit-probability scoring in defensive prioritization.",
  },
  {
    sourceId: "osv",
    name: "OSV",
    owner: "Open Source Vulnerabilities",
    url: "https://osv.dev/docs/",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for package vulnerability context and remediation evidence.",
  },
  {
    sourceId: "nasa_firms",
    name: "NASA FIRMS",
    owner: "NASA Earthdata",
    url: "https://firms.modaps.eosdis.nasa.gov/",
    accessPattern: "official_api",
    cadence: "realtime",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for active fire detection and regional fire-intelligence evidence packs.",
  },
  {
    sourceId: "nifc_wfigs",
    name: "NIFC / WFIGS",
    owner: "National Interagency Fire Center",
    url: "https://data-nifc.opendata.arcgis.com/",
    accessPattern: "official_api",
    cadence: "hourly",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for incident and perimeter context where available.",
  },
  {
    sourceId: "landfire",
    name: "LANDFIRE",
    owner: "U.S. Geological Survey and U.S. Forest Service",
    url: "https://landfire.gov/",
    accessPattern: "official_download",
    cadence: "annual",
    risk: "green",
    rights: publicAggregateRights,
    notes: "Use for fuels and vegetation context in wildfire planning packs.",
  },
  {
    sourceId: "nws_alerts",
    name: "NWS Alerts API",
    owner: "National Weather Service",
    url: "https://www.weather.gov/documentation/services-web-alerts",
    accessPattern: "official_api",
    cadence: "realtime",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for fire weather alerts and hazard context.",
  },
  {
    sourceId: "fema_nri",
    name: "FEMA National Risk Index",
    owner: "Federal Emergency Management Agency",
    url: "https://www.fema.gov/flood-maps/products-tools/national-risk-index",
    accessPattern: "official_download",
    cadence: "annual",
    risk: "green",
    rights: publicAggregateRights,
    notes: "Use for hazard, exposure, and vulnerability context in grant-ready packs.",
  },
  {
    sourceId: "faa_uas",
    name: "FAA UAS and TFR Data",
    owner: "Federal Aviation Administration",
    url: "https://www.faa.gov/uas",
    accessPattern: "official_api",
    cadence: "event_driven",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for drone-readiness constraints, airspace, TFR, LAANC, and public-safety caveats.",
  },
  {
    sourceId: "developer_docs_public",
    name: "Public Developer Documentation",
    owner: "Vendor-specific",
    url: "https://modelcontextprotocol.io/",
    accessPattern: "public_docs",
    cadence: "daily",
    risk: "yellow",
    rights: publicDocsRights,
    notes: "Use for endpoint, SDK, auth-scope, pricing, and changelog diff metadata where terms allow.",
  },
  {
    sourceId: "telegram_mini_apps_docs",
    name: "Telegram Mini Apps documentation",
    owner: "Telegram",
    url: "https://core.telegram.org/bots/webapps",
    accessPattern: "public_docs",
    cadence: "event_driven",
    risk: "yellow",
    rights: publicDocsRights,
    notes: "Use for Mini App launch modes, initData validation, and BotFather setup references. Treat Mira as a separate market/UX reference, not an official API dependency.",
  },
  {
    sourceId: "github_releases",
    name: "GitHub Releases",
    owner: "GitHub and repository maintainers",
    url: "https://docs.github.com/en/rest/releases",
    accessPattern: "official_api",
    cadence: "event_driven",
    risk: "yellow",
    rights: publicDocsRights,
    notes: "Use release metadata and links; respect repository licenses for code/content.",
  },
];

export const products: Product[] = [
  {
    productId: "opportunity_intel_pack",
    schemaId: "aoe.product.opportunity_intel_pack.v1",
    contractVersion: "v1",
    x402Stream: true,
    title: "Opportunity Intel Pack",
    route: "/v1/artifacts/:id/content",
    method: "GET",
    category: "opportunity_intelligence",
    priceUsd: "0.2500",
    artifactKind: "builder_opportunity_brief",
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    tags: ["x402", "grants", "rfp", "public-programs", "agent-buyable"],
    sourceIds: ["sam_gov_opportunities", "grants_gov", "regulations_gov", "data_gov_catalog", "census_acs"],
    buyerValue: "Turns fragmented public opportunities into fit-scored, source-cited action packets.",
    quality: {
      qualityTier: "sellable_mvp",
      contractCompleteness: "preview_quote_preflight_paid_content",
      evidenceDepth: "seeded_static_research",
      sourceFreshnessSla: freshnessSla("daily", 86_400, "Refresh official opportunity and regulatory sources daily before claiming current deadlines.", [
        "SAM.gov and some grants workflows may require API keys or official exports.",
        "Annual Census context can be older than daily opportunity records.",
        "Deadlines, amendments, and eligibility must be verified at the official source before submission.",
      ]),
      buyerValueMetrics: [
        {
          metricId: "fit_score_inputs",
          label: "Fit-score inputs",
          buyerFacingValue: "Shows why an opportunity matches a buyer profile instead of returning a generic list.",
          measuredBy: "Opportunity source count, eligibility fields, geography, deadline, and required-document coverage.",
        },
        {
          metricId: "deadline_triage",
          label: "Deadline triage",
          buyerFacingValue: "Surfaces source-linked next actions before a filing window is missed.",
          measuredBy: "Deadline, amendment, agency, and source-link fields present in each accepted match.",
        },
      ],
      auditSignals: ["source ids", "retrieval timestamps", "eligibility fields", "deadline proof", "rights envelope"],
    },
    disclaimers: ["Not legal advice.", "Not an official agency determination.", "Verify deadlines at the source before filing."],
  },
  {
    productId: "cyber_exploited_vuln_priority",
    schemaId: "aoe.product.cyber_exploited_vuln_priority.v1",
    contractVersion: "v1",
    x402Stream: true,
    title: "Exploited Vulnerability Priority Pack",
    route: "/v1/artifacts/:id/content",
    method: "GET",
    category: "defensive_cyber",
    priceUsd: "0.5000",
    artifactKind: "vulnerability_priority_report",
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    tags: ["cyber", "kev", "epss", "nvd", "defensive-only"],
    sourceIds: ["cisa_kev", "nvd_cve", "first_epss", "osv"],
    buyerValue: "Ranks what to fix today using public exploit evidence and defensive remediation context.",
    quality: {
      qualityTier: "sellable_mvp",
      contractCompleteness: "preview_quote_preflight_adapter",
      evidenceDepth: "live_adapter_plus_seeded_artifact",
      sourceFreshnessSla: freshnessSla("daily", 86_400, "Refresh CISA KEV, FIRST EPSS, NVD, and OSV daily before paid remediation packets are sold as current.", [
        "EPSS probabilities and NVD enrichment can lag newly disclosed vulnerabilities.",
        "No active scanning is performed by this product.",
        "Customer asset criticality must come from an authorized buyer inventory.",
      ]),
      buyerValueMetrics: [
        {
          metricId: "fix_now_queue",
          label: "Fix-now queue",
          buyerFacingValue: "Converts a noisy CVE list into a source-cited remediation order.",
          measuredBy: "Known-exploited flag, EPSS percentile, severity, affected product, and remediation evidence coverage.",
        },
        {
          metricId: "defensive_proof_pack",
          label: "Defensive proof pack",
          buyerFacingValue: "Gives MSPs a client-ready explanation without exploit instructions.",
          measuredBy: "Evidence-card count, source links, caveat coverage, and absence of offensive payload fields.",
        },
      ],
      auditSignals: ["KEV match", "EPSS score", "NVD CVSS", "OSV package context", "defensive caveats"],
    },
    disclaimers: ["Defensive prioritization only.", "No exploit payloads or credential material.", "Scan only assets you own or are authorized to assess."],
  },
  {
    productId: "market_regime_evidence_pack",
    schemaId: "aoe.product.market_regime_evidence_pack.v1",
    contractVersion: "v1",
    x402Stream: true,
    title: "Market Regime Evidence Pack",
    route: "/v1/artifacts/:id/content",
    method: "GET",
    category: "market_intelligence",
    priceUsd: "1.0000",
    artifactKind: "market_regime_report",
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    tags: ["markets", "macro", "filings", "research-only", "no-execution"],
    sourceIds: ["fred_alfred", "cftc_cot", "sec_edgar"],
    buyerValue: "Packages macro, public positioning, and filing signals into non-advisory research artifacts with explicit source freshness and provenance.",
    quality: {
      qualityTier: "sellable_mvp",
      contractCompleteness: "preview_quote_preflight_adapter",
      evidenceDepth: "live_adapter_plus_seeded_artifact",
      sourceFreshnessSla: freshnessSla("weekly", 604_800, "Refresh public macro, filing, and positioning evidence at least weekly; live preview routes should fetch SEC and FRED at request time.", [
        "CFTC positioning is weekly, FRED series can revise, and SEC availability can rate-limit or degrade.",
        "The active paid contract is limited to public SEC, FRED, and CFTC evidence until any future licensed sources pass separate terms review.",
        "Outputs are research context only and never personalized investment advice or execution.",
      ]),
      buyerValueMetrics: [
        {
          metricId: "evidence_domain_coverage",
          label: "Evidence-domain coverage",
          buyerFacingValue: "Combines macro, filings, and positioning context in one buyer-readable packet.",
          measuredBy: "Distinct public source domains represented, latest observation dates, filing count, and caveat coverage.",
        },
        {
          metricId: "non_advisory_guardrail",
          label: "Non-advisory guardrail",
          buyerFacingValue: "Keeps the artifact sellable without creating a trade-advice or execution surface.",
          measuredBy: "No buy/sell/hold fields, no price targets, no portfolio personalization, and no trade route.",
        },
      ],
      auditSignals: ["SEC filing links", "FRED observation dates", "CFTC vintage", "public-source-only contract", "research-only policy"],
    },
    disclaimers: ["Research and education only.", "Not investment advice.", "No buy/sell/hold recommendations.", "No trade execution."],
  },
  {
    productId: "developer_api_change_radar",
    schemaId: "aoe.product.developer_api_change_radar.v1",
    contractVersion: "v1",
    x402Stream: true,
    title: "Developer API Change Radar",
    route: "/v1/artifacts/:id/content",
    method: "GET",
    category: "developer_intelligence",
    priceUsd: "0.2500",
    artifactKind: "api_change_radar",
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    tags: ["developer-docs", "api", "sdk", "agent-builders"],
    sourceIds: ["developer_docs_public", "github_releases"],
    buyerValue: "Flags API, SDK, auth, pricing, and docs changes before agents generate stale code.",
    quality: {
      qualityTier: "sellable_mvp",
      contractCompleteness: "preview_quote_preflight_paid_content",
      evidenceDepth: "seeded_static_research",
      sourceFreshnessSla: freshnessSla("daily", 86_400, "Refresh public docs and release metadata daily before claiming a change radar is current.", [
        "Public docs and release notes can have vendor-specific reuse terms.",
        "Generated summaries must stay short, source-linked, and unofficial.",
        "Snippet status is only current when backed by a same-day test result.",
      ]),
      buyerValueMetrics: [
        {
          metricId: "change_detection_fields",
          label: "Change-detection fields",
          buyerFacingValue: "Identifies API, SDK, auth, pricing, and breaking-change drift before agents write stale code.",
          measuredBy: "Endpoint names, package versions, release ids, changelog links, and tested/stale status coverage.",
        },
        {
          metricId: "migration_impact",
          label: "Migration impact",
          buyerFacingValue: "Turns source changes into concise implementation-risk notes for builders.",
          measuredBy: "Breaking-change flag, affected surface, source link, and recommended verification command coverage.",
        },
      ],
      auditSignals: ["release ids", "source doc links", "package versions", "snippet test status", "vendor terms caveats"],
    },
    disclaimers: ["Unofficial derived analysis.", "Verify source docs before production changes.", "No vendor certification implied."],
  },
];

export const streams: StreamDefinition[] = [
  {
    streamId: "sec_macro_context",
    productId: "market_regime_evidence_pack",
    x402Stream: true,
    title: "Live SEC/FRED Upstream Proof",
    route: "/v1/streams/market-context/live-proof",
    method: "POST",
    previewPriceUsd: "1.0000",
    schemaVersion: "aoe.market_live_upstream_proof.v1",
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    sourceIds: ["sec_edgar", "fred_alfred"],
    tags: ["markets", "macro", "filings", "research-only", "agent-buyable"],
    inputSchema: {
      ticker: "required public company ticker, 1-12 chars",
      seriesIds: "optional FRED series ids, default FEDFUNDS/UNRATE/CPIAUCSL",
      filingForms: "optional SEC filing forms, default 10-K/10-Q/8-K",
      filingLimit: "optional 1-25",
      seriesLimit: "optional 1-24 observations per series",
    },
    outputSummary: "Live SEC/FRED upstream availability, freshness, source URLs, evidence hashes, and research-only boundaries.",
    historicalClaimsPolicy: {
      revisionAware: false,
      liveMacroReadMode: "fred_graph_csv",
      productionHistoricalClaimsRequire: "alfred_vintages",
      notes: [
        "Live route proves current SEC/FRED reachability and freshness only.",
        "Historical or revision-sensitive macro claims require explicit ALFRED vintages before resale.",
      ],
    },
    caveats: [
      "Research context only.",
      "Not investment advice.",
      "No buy/sell/hold recommendation.",
      "No trade execution.",
    ],
  },
];

export const artifacts: Artifact[] = [
  {
    artifactId: "aoe_public_program_data_opportunity",
    productId: "opportunity_intel_pack",
    x402Stream: true,
    title: "Public Program and Data Opportunity Brief",
    category: "opportunity_intelligence",
    description: "A source-cited profile for grants, RFPs, local programs, and public datasets that match a builder or operator profile.",
    tags: ["grants", "rfp", "public-programs", "datasets", "public-sector"],
    sourceIds: ["sam_gov_opportunities", "grants_gov", "data_gov_catalog", "census_acs"],
    rights: publicOfficialRights,
    preview: {
      headline: "Find public-sector opportunities and relevant datasets without turning the product into a crawler.",
      audience: ["grant_writers", "founders", "economic_development_groups", "agent_builders"],
      dataPoints: ["deadline", "agency", "eligibility", "award_range", "required_documents", "source_vintage"],
      sampleQuestions: ["Which opportunities fit this buyer profile?", "What source evidence is needed before a bid/no-bid decision?"],
      freshness: { class: "daily", ttlSeconds: 86_400, lastVerified: "seeded_static_research_2026-05-08" },
    },
    content: {
      summary: "Use official opportunity portals and public datasets to package a bid/no-bid brief for builders, operators, and agents. The x402 stream sells normalized evidence, eligibility context, and source proof, not raw portal resale.",
      evidenceCards: [
        {
          title: "Opportunity fit starts with public notices, not bespoke scraping.",
          sourceIds: ["sam_gov_opportunities", "grants_gov"],
          finding: "Federal contract and grant portals expose enough metadata for first-pass eligibility, deadlines, and required-document triage.",
          action: "Build profile inputs for geography, applicant type, capabilities, and target award size before ranking opportunities.",
        },
        {
          title: "Regional context makes the artifact sellable.",
          sourceIds: ["data_gov_catalog", "census_acs"],
          finding: "A buyer needs geography, workforce, market, and program-fit context more than another generic opportunity list.",
          action: "Attach source vintage warnings when daily opportunities are mixed with annual Census data.",
        },
      ],
      nextActions: [
        "Create buyer profiles for founders, agencies, consultants, and regional operators.",
        "Add a daily source-refresh job before claiming current opportunity status.",
        "Export the accepted matches to a proposal tracker with source links and deadline proof.",
      ],
      caveats: ["This is not a legal eligibility determination.", "Deadlines and amendments must be verified at the official source before submission."],
      outputPolicy: ["Return derived facts, source links, checklist items, and short attributed snippets only.", "Never resell raw source documents as the product."],
    },
  },
  {
    artifactId: "aoe_cyber_kev_epss_priority",
    productId: "cyber_exploited_vuln_priority",
    x402Stream: true,
    title: "MSP Exploited Vulnerability Priority Pack",
    category: "defensive_cyber",
    description: "A defensive report that ranks vulnerabilities using CISA KEV, EPSS, NVD, and OSV context without exploit instructions.",
    tags: ["cyber", "msp", "smb", "kev", "epss", "remediation"],
    sourceIds: ["cisa_kev", "nvd_cve", "first_epss", "osv"],
    rights: publicOfficialRights,
    preview: {
      headline: "Tell a small team what to fix today, prove why, and avoid drowning them in CVEs.",
      audience: ["MSPs", "fractional_IT", "SMB_security", "cyber_insurance_support"],
      dataPoints: ["cve", "kev_status", "epss_percentile", "affected_product", "remediation", "proof_links"],
      sampleQuestions: ["Which CVEs from my asset list are known exploited?", "What evidence should go into the client remediation packet?"],
      freshness: { class: "daily", ttlSeconds: 86_400, lastVerified: "seeded_static_research_2026-05-08" },
    },
    content: {
      summary: "The defensible cyber wedge is a paid exploited-vulnerability priority API and human-readable proof packet. It should rank fix-now items using public exploitation evidence and never provide exploit payloads or stolen material.",
      evidenceCards: [
        {
          title: "Known exploitation beats raw severity for urgency.",
          sourceIds: ["cisa_kev", "first_epss"],
          finding: "KEV and EPSS are practical signals for moving from a noisy CVE list to a fix-now queue.",
          action: "Sort by known exploitation, exploit probability, exposure, affected asset criticality, and remediation availability.",
        },
        {
          title: "Package remediation as proof, not panic.",
          sourceIds: ["nvd_cve", "osv"],
          finding: "SMB/MSP buyers need a clear ticket list with version evidence, source links, and remediation notes.",
          action: "Return PDF/JSON-ready findings with no offensive steps or PoC references.",
        },
      ],
      nextActions: [
        "Accept asset inventory exports before any active scanning.",
        "Add customer authorization proof for domain/cloud scans.",
        "Map output to NIST CSF 2.0 and PCI-style evidence packets.",
      ],
      caveats: ["Defensive use only.", "No unauthorized scanning.", "No exploit code.", "No raw credentials or breach dumps."],
      outputPolicy: ["Return metadata, risk ranking, remediation, and citations.", "Suppress exploit instructions and weaponized indicators by default."],
    },
  },
  {
    artifactId: "aoe_macro_regime_public_evidence",
    productId: "market_regime_evidence_pack",
    x402Stream: true,
    title: "Macro Regime and Cross-Asset Evidence Pack",
    category: "market_intelligence",
    description: "A non-advisory market-intelligence artifact using public macro, positioning, and filings sources.",
    tags: ["macro", "markets", "research-only", "filings", "positioning"],
    sourceIds: ["fred_alfred", "cftc_cot", "sec_edgar"],
    rights: publicOfficialRights,
    preview: {
      headline: "Sell explainable research artifacts, not trading automation or personalized advice.",
      audience: ["research_analysts", "founders", "operators", "agents", "market_research_buyers"],
      dataPoints: ["liquidity", "rates", "inflation", "positioning", "filing_changes", "source_vintage"],
      sampleQuestions: ["What changed in the macro regime this week?", "Which filings or flows explain the risk narrative?"],
      freshness: { class: "weekly", ttlSeconds: 604_800, lastVerified: "seeded_static_research_2026-05-08" },
    },
    content: {
      summary: "The safe market wedge is paid research and evidence packs built from public macro, filing, and positioning evidence. The product should avoid personalized advice, licensed raw vendor payloads, and all live execution.",
      evidenceCards: [
        {
          title: "Public macro and filings data are strong revenue inputs.",
          sourceIds: ["fred_alfred", "sec_edgar", "cftc_cot"],
          finding: "Macroeconomic series, COT positioning, and EDGAR filings are public, high-demand inputs for research automation.",
          action: "Build repeatable evidence packs with revision dates, methodology, and source links.",
        },
        {
          title: "Keep the active contract public-source only.",
          sourceIds: ["fred_alfred", "sec_edgar"],
          finding: "The current storefront proof is strongest when the paid contract matches the live SEC/FRED evidence route and public-source posture.",
          action: "Keep licensed onchain, vendor, or narrative expansions in a separate backlog until terms review and dedicated contracts exist.",
        },
      ],
      nextActions: [
        "Keep the live proof anchored on SEC/FRED freshness and provenance.",
        "Add CFTC-backed weekly positioning overlays without changing the public-source rights posture.",
        "Design any licensed market expansion as a separate contract instead of broadening this active product silently.",
      ],
      caveats: ["Not investment advice.", "No buy/sell/hold recommendations.", "No trade execution.", "Data may be delayed or incomplete."],
      outputPolicy: ["Return research context and reproducible assumptions.", "Do not personalize recommendations to a buyer portfolio."],
    },
  },
  {
    artifactId: "aoe_x402_api_change_radar",
    productId: "developer_api_change_radar",
    x402Stream: true,
    title: "x402 and Agent Payments API Change Radar",
    category: "developer_intelligence",
    description: "A public-docs change radar for x402, MCP, and agent-payment infrastructure.",
    tags: ["x402", "mcp", "developer-docs", "api-change", "agent-payments"],
    sourceIds: ["developer_docs_public", "github_releases"],
    rights: publicDocsRights,
    preview: {
      headline: "Reduce stale agent code by selling tested, source-cited API change summaries.",
      audience: ["agent_builders", "devrel", "developer_tooling_founders", "technical_consultants"],
      dataPoints: ["endpoint", "sdk_version", "network_support", "auth_scope", "pricing_change", "breaking_change"],
      sampleQuestions: ["Which x402 SDK examples changed this week?", "Which docs are tested versus untested?"],
      freshness: { class: "daily", ttlSeconds: 86_400, lastVerified: "seeded_static_research_2026-05-08" },
    },
    content: {
      summary: "Developer API-change radar is a clean demo vertical: public docs and releases become a paid diff, test-status, and migration-impact artifact for agents before they generate code.",
      evidenceCards: [
        {
          title: "Docs are source material, not a license-free training corpus.",
          sourceIds: ["developer_docs_public"],
          finding: "The safe output is a short sourced diff and tested contract note, not a copy of the docs.",
          action: "Track endpoint names, auth scopes, package versions, and source links with a source-rights envelope.",
        },
        {
          title: "Release metadata creates objective freshness.",
          sourceIds: ["github_releases"],
          finding: "Release tags and changelogs are useful machine-readable triggers for docs and SDK monitors.",
          action: "Store release ids, timestamps, hashes, and test status for every derived radar item.",
        },
      ],
      nextActions: [
        "Add a docs-diff worker for x402, MCP, Hono, and Cloudflare Agents docs.",
        "Mark every snippet tested, untested, stale, or auth-blocked.",
        "Expose an MCP search/quote/fetch flow after the REST kernel stabilizes.",
      ],
      caveats: ["Unofficial derived analysis.", "No vendor certification.", "Verify source docs before production changes."],
      outputPolicy: ["Return metadata, links, and short attributed summaries.", "Do not republish full docs or gated content."],
    },
  },
];

export const separateWorkstreams: SeparateWorkstream[] = [
  {
    workstreamId: "wildfire_drone_readiness_lane",
    title: "Regional Wildfire and Drone Readiness",
    category: "separate_operational_research",
    x402Stream: false,
    tags: ["wildfire", "drone-readiness", "public-safety", "planning-only"],
    sourceIds: ["nasa_firms", "nifc_wfigs", "landfire", "nws_alerts", "fema_nri", "faa_uas", "census_acs"],
    publicPreviewEndpoints: ["/v1/adapters/wildfire/alerts/preview", "/v1/adapters/wildfire/wfigs-perimeters/preview"],
    boundary: [
      "Separate from the x402 paid-stream catalog.",
      "Read-only planning and situational awareness only.",
      "No incident command, alert sends, dispatch, flight authorization, or drone operations.",
    ],
    status: "separate_read_only_lane",
  },
];

function uniqueSourceIds(records: Array<{ sourceIds: string[] }>): string[] {
  return [...new Set(records.flatMap((record) => record.sourceIds))].sort();
}

function productFreshness(productId: string): SourceFreshnessSla | undefined {
  return products.find((product) => product.productId === productId)?.quality.sourceFreshnessSla;
}

export const productRoutes: RouteDiscovery[] = [
  {
    routeId: "product_discovery",
    route: "/v1/products",
    method: "GET",
    schemaId: "aoe.discovery.products.v1",
    x402Stream: false,
    productIds: products.map((product) => product.productId),
    access: "public",
    readiness: "live_read_only",
    sourceIds: [],
    value: "Lists sellable product contracts with schema ids, buyer value, quality metadata, and source freshness caveats.",
    caveats: ["Registry freshness is deploy-bound; source freshness is declared per product."],
  },
  {
    routeId: "route_discovery",
    route: "/v1/routes",
    method: "GET",
    schemaId: "aoe.discovery.routes.v1",
    x402Stream: false,
    productIds: products.map((product) => product.productId),
    access: "public",
    readiness: "live_read_only",
    sourceIds: [],
    value: "Agent-readable route map for previews, quotes, preflight checks, simulated/testnet paid content, and separate read-only lanes.",
    caveats: ["Route discovery is a contract map, not proof that upstream sources are currently reachable."],
  },
  {
    routeId: "demo_guide",
    route: "/v1/demo-guide",
    method: "GET",
    schemaId: "aoe.demo_guide.v1",
    x402Stream: false,
    productIds: products.map((product) => product.productId),
    access: "public",
    readiness: "live_read_only",
    sourceIds: [],
    value: "Machine-readable demo and developer integration guide for judges, buyers, and agents.",
    caveats: ["Guide commands are public and side-effect free; paid artifact unlock remains simulated or Base Sepolia testnet only."],
  },
  {
    routeId: "telegram_status",
    route: "/v1/telegram/status",
    method: "GET",
    schemaId: "aoe.telegram.status.v1",
    x402Stream: false,
    productIds: products.map((product) => product.productId),
    access: "public",
    readiness: "live_read_only",
    sourceIds: ["telegram_mini_apps_docs"],
    value: "Reports Telegram Mini App registration posture, BotFather setup requirements, and disabled-send safety boundaries.",
    caveats: ["No webhook registration or outbound Telegram sends occur from this endpoint.", "Mira is referenced as market context, not an official Telegram API dependency."],
  },
  {
    routeId: "telegram_registration",
    route: "/v1/telegram/register",
    method: "POST",
    schemaId: "aoe.telegram.registration.v1",
    x402Stream: false,
    productIds: products.map((product) => product.productId),
    access: "public",
    readiness: "key_required",
    sourceIds: ["telegram_mini_apps_docs"],
    value: "Verifies Telegram Mini App initData server-side and returns a non-secret opt-in registration receipt without sending Telegram messages.",
    caveats: [
      "Requires AOE_TELEGRAM_BOT_TOKEN before real registration succeeds.",
      "Raw initData is never echoed.",
      "No persistent opt-in storage, webhook registration, or outbound Telegram sends are enabled in this slice.",
    ],
  },
  {
    routeId: "x402_status",
    route: "/v1/x402/status",
    method: "GET",
    schemaId: "aoe.x402.status.v1",
    x402Stream: false,
    productIds: products.map((product) => product.productId),
    access: "public",
    readiness: "live_read_only",
    sourceIds: [],
    value: "Reports whether paid content is using the simulated header rail or the official Base Sepolia x402 testnet middleware.",
    caveats: ["Mainnet settlement is blocked.", "The server must never store buyer private keys."],
  },
  {
    routeId: "artifact_index",
    route: "/v1/artifacts",
    method: "GET",
    schemaId: "aoe.discovery.artifacts.v1",
    x402Stream: true,
    productIds: products.map((product) => product.productId),
    access: "public",
    readiness: "live_read_only",
    sourceIds: uniqueSourceIds(artifacts),
    value: "Public previews for paid artifacts without exposing full content.",
    caveats: ["Preview freshness follows the artifact preview metadata and product source freshness SLA."],
  },
  {
    routeId: "artifact_preview",
    route: "/v1/artifacts/:id/preview",
    method: "GET",
    schemaId: "aoe.artifact.preview.v1",
    x402Stream: true,
    productIds: products.map((product) => product.productId),
    access: "public",
    readiness: "live_read_only",
    sourceIds: uniqueSourceIds(artifacts),
    value: "Buyer-safe preview that includes source ids, rights envelope, and freshness metadata without full paid content.",
    caveats: ["Preview facts can be seeded or live depending on the artifact; check preview.freshness before treating it as current."],
  },
  {
    routeId: "artifact_quote",
    route: "/v1/artifacts/:id/quote",
    method: "GET",
    schemaId: "aoe.artifact.quote.v1",
    x402Stream: true,
    productIds: products.map((product) => product.productId),
    access: "public",
    readiness: "live_read_only",
    sourceIds: uniqueSourceIds(artifacts),
    value: "Returns an x402 quote, work order id, rights envelope, and source ids before payment.",
    caveats: ["Quotes are simulated or Base Sepolia testnet only and expire quickly; do not send mainnet funds to any demo payTo address."],
  },
  {
    routeId: "access_preflight",
    route: "/v1/access/preflight",
    method: "POST",
    schemaId: "aoe.access.preflight.v1",
    x402Stream: true,
    productIds: products.map((product) => product.productId),
    access: "public",
    readiness: "live_read_only",
    sourceIds: uniqueSourceIds(artifacts),
    value: "Lets agents check price caps, source allow-lists, settlement mode, side-effect posture, and contract metadata before access.",
    caveats: ["Preflight does not authorize raw source resale or bypass source terms."],
  },
  {
    routeId: "artifact_paid_content",
    route: "/v1/artifacts/:id/content",
    method: "GET",
    schemaId: "aoe.artifact.content.v1",
    x402Stream: true,
    productIds: products.map((product) => product.productId),
    access: "simulated_x402_payment",
    readiness: "simulated_payment_required",
    sourceIds: uniqueSourceIds(artifacts),
    value: "Unlocks derived artifact content and non-secret receipts after simulated payment or official Base Sepolia x402 testnet settlement.",
    caveats: ["No mainnet/live settlement is enabled.", "Paid content is derived analysis and metadata, not raw source resale."],
  },
  {
    routeId: "cyber_vuln_priority_preview",
    route: "/v1/adapters/cyber/vuln-priority/preview",
    method: "POST",
    schemaId: "aoe.adapter.cyber_vuln_priority.preview.v1",
    x402Stream: true,
    productIds: ["cyber_exploited_vuln_priority"],
    access: "public",
    readiness: "live_read_only",
    sourceIds: ["cisa_kev", "first_epss", "nvd_cve"],
    value: "Live read-only defensive preview for buyer CVE lists before purchasing a remediation packet.",
    freshnessSla: productFreshness("cyber_exploited_vuln_priority"),
    caveats: ["No active scanning.", "No exploit payloads.", "Customer inventory must be authorized."],
  },
  {
    routeId: "cyber_inventory_priority_preview",
    route: "/v1/adapters/cyber/inventory-priority/preview",
    method: "POST",
    schemaId: "sapphirealpha.cyber_inventory_priority.preview.v1",
    x402Stream: true,
    productIds: ["cyber_exploited_vuln_priority"],
    access: "public",
    readiness: "live_read_only",
    sourceIds: ["cisa_kev", "first_epss", "nvd_cve"],
    value: "Buyer-proof defensive preview that maps authorized asset inventory rows to live CVE priority evidence before purchase.",
    freshnessSla: productFreshness("cyber_exploited_vuln_priority"),
    caveats: ["No active scanning.", "No exploit payloads.", "No credential material.", "Customer inventory must be authorized."],
  },
  {
    routeId: "market_context_preview",
    route: "/v1/streams/market-context/preview",
    method: "POST",
    schemaId: "sapphirealpha.market_context.v1",
    x402Stream: true,
    productIds: ["market_regime_evidence_pack"],
    access: "public",
    readiness: "live_read_only",
    sourceIds: ["sec_edgar", "fred_alfred"],
    value: "Live read-only SEC plus macro preview for non-advisory market research buyers.",
    freshnessSla: productFreshness("market_regime_evidence_pack"),
    caveats: ["SEC can rate-limit; degraded responses must be labeled partial.", "No investment advice, price target, or trade execution."],
  },
  {
    routeId: "market_context_live_proof",
    route: "/v1/streams/market-context/live-proof",
    method: "POST",
    schemaId: "aoe.market_live_upstream_proof.v1",
    x402Stream: true,
    productIds: ["market_regime_evidence_pack"],
    access: "public",
    readiness: "live_read_only",
    sourceIds: ["sec_edgar", "fred_alfred"],
    value: "Live upstream proof that SEC EDGAR and FRED were reached now, with source URLs, freshness, latency, hashes, and no-mock-data posture.",
    freshnessSla: productFreshness("market_regime_evidence_pack"),
    caveats: [
      "This is a source-availability and provenance proof, not investment advice.",
      "SEC and FRED can rate-limit or change terms; failures must remain visible.",
      "No payment settlement, wallet signing, order execution, or external side effect occurs.",
    ],
  },
  {
    routeId: "sec_filings_preview",
    route: "/v1/adapters/markets/sec-filings/preview",
    method: "POST",
    schemaId: "aoe.adapter.sec_filings.preview.v1",
    x402Stream: true,
    productIds: ["market_regime_evidence_pack"],
    access: "public",
    readiness: "live_read_only",
    sourceIds: ["sec_edgar"],
    value: "Public filing metadata preview that can feed paid research artifacts.",
    freshnessSla: productFreshness("market_regime_evidence_pack"),
    caveats: ["Document intelligence only.", "No portfolio personalization or trade execution."],
  },
  {
    routeId: "fred_series_preview",
    route: "/v1/adapters/markets/fred-series/preview",
    method: "POST",
    schemaId: "aoe.adapter.fred_series.preview.v1",
    x402Stream: true,
    productIds: ["market_regime_evidence_pack"],
    access: "public",
    readiness: "live_read_only",
    sourceIds: ["fred_alfred"],
    value: "Public macro series preview for evidence packs and source freshness checks.",
    freshnessSla: productFreshness("market_regime_evidence_pack"),
    caveats: ["FRED graph CSV is not revision-aware; use ALFRED vintages for production-grade historical claims."],
  },
  {
    routeId: "wildfire_alerts_preview",
    route: "/v1/adapters/wildfire/alerts/preview",
    method: "POST",
    schemaId: "aoe.workstream.wildfire_alerts.preview.v1",
    x402Stream: false,
    productIds: [],
    workstreamIds: ["wildfire_drone_readiness_lane"],
    access: "public",
    readiness: "separate_read_only_lane",
    sourceIds: ["nws_alerts"],
    value: "Separate read-only wildfire weather preview, intentionally outside paid x402 streams.",
    caveats: ["Not incident command.", "No alert sends, dispatch, flight authorization, or drone operations."],
  },
  {
    routeId: "wildfire_wfigs_perimeters_preview",
    route: "/v1/adapters/wildfire/wfigs-perimeters/preview",
    method: "POST",
    schemaId: "aoe.workstream.wfigs_perimeters.preview.v1",
    x402Stream: false,
    productIds: [],
    workstreamIds: ["wildfire_drone_readiness_lane"],
    access: "public",
    readiness: "separate_read_only_lane",
    sourceIds: ["nifc_wfigs"],
    value: "Separate read-only WFIGS perimeter preview, intentionally outside paid x402 streams.",
    caveats: ["Perimeters are not available for every incident.", "Not evacuation authority or incident command."],
  },
];

export function getProduct(productId: string): Product | undefined {
  return products.find((product) => product.productId === productId);
}

export function getArtifact(artifactId: string): Artifact | undefined {
  return artifacts.find((artifact) => artifact.artifactId === artifactId);
}

export function getSource(sourceId: string): SourceRecord | undefined {
  return sources.find((source) => source.sourceId === sourceId);
}
