import type { Artifact, Product, RightsEnvelope, SourceRecord } from "./types.js";

const publicOfficialRights: RightsEnvelope = {
  licenseId: "public_official_derived_facts",
  allowedUses: ["read", "summarize", "fact_extract", "cite", "private_cache", "derived_analysis"],
  prohibitedUses: ["resell_raw_source", "claim_official_endorsement", "train_without_license", "remove_attribution"],
  cacheTtlSeconds: 86_400,
  maxExtract: "facts, metadata, links, and short attributed excerpts only",
  attribution: "Source links, retrieval timestamps, and agency/source names required.",
  privacyClass: "public",
  redistribution: "derived_facts_with_citation",
};

const publicAggregateRights: RightsEnvelope = {
  ...publicOfficialRights,
  licenseId: "public_aggregate_derived_facts",
  privacyClass: "public_aggregate",
  cacheTtlSeconds: 604_800,
};

const publicDocsRights: RightsEnvelope = {
  licenseId: "public_docs_with_source_terms",
  allowedUses: ["read", "summarize", "fact_extract", "cite", "private_cache", "diff_metadata"],
  prohibitedUses: ["resell_raw_docs", "train_without_license", "claim_vendor_certification", "bypass_auth_or_paywall"],
  cacheTtlSeconds: 86_400,
  maxExtract: "facts, changelog metadata, endpoint names, and short attributed excerpts only",
  attribution: "Vendor documentation and repository links required.",
  privacyClass: "public",
  redistribution: "derived_facts_with_citation",
};

const licensedApiRights: RightsEnvelope = {
  licenseId: "licensed_api_required_before_resale",
  allowedUses: ["metadata_only_until_license_review", "private_cache_if_terms_allow"],
  prohibitedUses: ["redistribute_raw_source", "bypass_rate_limits", "evade_api_terms", "train_without_license"],
  cacheTtlSeconds: 3_600,
  maxExtract: "metadata and derived analysis only until terms are approved",
  attribution: "Provider attribution and terms review required.",
  privacyClass: "source_terms_dependent",
  redistribution: "blocked_until_license_review",
};

export const sources: SourceRecord[] = [
  {
    sourceId: "sam_gov_opportunities",
    name: "SAM.gov Contract Opportunities",
    owner: "U.S. General Services Administration",
    url: "https://sam.gov/content/opportunities",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for contract opportunity metadata, amendments, deadlines, agency names, NAICS/PSC, and source links.",
  },
  {
    sourceId: "grants_gov",
    name: "Grants.gov",
    owner: "U.S. Department of Health and Human Services",
    url: "https://www.grants.gov/",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for grant opportunity metadata, eligibility, deadlines, award ranges, and application package links.",
  },
  {
    sourceId: "regulations_gov",
    name: "Regulations.gov",
    owner: "U.S. eRulemaking Program",
    url: "https://www.regulations.gov/developers",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for docket metadata, comment windows, effective dates, and non-legal deadline watches.",
  },
  {
    sourceId: "data_gov_catalog",
    name: "Data.gov Catalog",
    owner: "U.S. General Services Administration",
    url: "https://catalog.data.gov/",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use as a discovery index for official public datasets and source-of-truth links.",
  },
  {
    sourceId: "census_acs",
    name: "U.S. Census ACS and Business Patterns",
    owner: "U.S. Census Bureau",
    url: "https://www.census.gov/data/developers.html",
    accessPattern: "official_api",
    cadence: "annual",
    risk: "green",
    rights: publicAggregateRights,
    notes: "Use for regional demographics, business-density context, and WUI/community exposure normalization.",
  },
  {
    sourceId: "fred_alfred",
    name: "FRED and ALFRED",
    owner: "Federal Reserve Bank of St. Louis",
    url: "https://fred.stlouisfed.org/docs/api/fred/",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for macro series and revision-aware evidence packs. Some API access requires a key.",
  },
  {
    sourceId: "cftc_cot",
    name: "CFTC Commitments of Traders",
    owner: "U.S. Commodity Futures Trading Commission",
    url: "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm",
    accessPattern: "official_download",
    cadence: "weekly",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for positioning context in non-advisory market-regime evidence packs.",
  },
  {
    sourceId: "sec_edgar",
    name: "SEC EDGAR APIs",
    owner: "U.S. Securities and Exchange Commission",
    url: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
    accessPattern: "official_api",
    cadence: "event_driven",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for public filings metadata, company facts, risk-factor diffs, and filing-change detection.",
  },
  {
    sourceId: "defillama",
    name: "DefiLlama",
    owner: "DefiLlama contributors",
    url: "https://defillama.com/docs/api",
    accessPattern: "open_data",
    cadence: "daily",
    risk: "yellow",
    rights: licensedApiRights,
    notes: "Treat as terms-reviewed open/partner data before redistribution; use derived market-structure analysis.",
  },
  {
    sourceId: "coingecko",
    name: "CoinGecko API",
    owner: "CoinGecko",
    url: "https://docs.coingecko.com/",
    accessPattern: "partner_api",
    cadence: "realtime",
    risk: "yellow",
    rights: licensedApiRights,
    notes: "Use only according to API plan and redistribution terms. Good signal for x402 pay-per-use market data.",
  },
  {
    sourceId: "gdelt_2",
    name: "GDELT 2.0",
    owner: "GDELT Project",
    url: "https://www.gdeltproject.org/",
    accessPattern: "open_data",
    cadence: "realtime",
    risk: "yellow",
    rights: licensedApiRights,
    notes: "Use metadata and derived event/narrative analysis; review source-level content rights before quoting.",
  },
  {
    sourceId: "cisa_kev",
    name: "CISA Known Exploited Vulnerabilities",
    owner: "Cybersecurity and Infrastructure Security Agency",
    url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
    accessPattern: "official_download",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for defensive vulnerability prioritization and proof packets.",
  },
  {
    sourceId: "nvd_cve",
    name: "NVD CVE API 2.0",
    owner: "National Institute of Standards and Technology",
    url: "https://nvd.nist.gov/developers/vulnerabilities",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for CVE metadata, CVSS, CPE context, and KEV flags.",
  },
  {
    sourceId: "first_epss",
    name: "FIRST EPSS",
    owner: "Forum of Incident Response and Security Teams",
    url: "https://api.first.org/epss/",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for exploit-probability scoring in defensive prioritization.",
  },
  {
    sourceId: "osv",
    name: "OSV",
    owner: "Open Source Vulnerabilities",
    url: "https://osv.dev/docs/",
    accessPattern: "official_api",
    cadence: "daily",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for package vulnerability context and remediation evidence.",
  },
  {
    sourceId: "nasa_firms",
    name: "NASA FIRMS",
    owner: "NASA Earthdata",
    url: "https://firms.modaps.eosdis.nasa.gov/",
    accessPattern: "official_api",
    cadence: "realtime",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for active fire detection and regional fire-intelligence evidence packs.",
  },
  {
    sourceId: "nifc_wfigs",
    name: "NIFC / WFIGS",
    owner: "National Interagency Fire Center",
    url: "https://data-nifc.opendata.arcgis.com/",
    accessPattern: "official_api",
    cadence: "hourly",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for incident and perimeter context where available.",
  },
  {
    sourceId: "landfire",
    name: "LANDFIRE",
    owner: "U.S. Geological Survey and U.S. Forest Service",
    url: "https://landfire.gov/",
    accessPattern: "official_download",
    cadence: "annual",
    risk: "green",
    rights: publicAggregateRights,
    notes: "Use for fuels and vegetation context in wildfire planning packs.",
  },
  {
    sourceId: "nws_alerts",
    name: "NWS Alerts API",
    owner: "National Weather Service",
    url: "https://www.weather.gov/documentation/services-web-alerts",
    accessPattern: "official_api",
    cadence: "realtime",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for fire weather alerts and hazard context.",
  },
  {
    sourceId: "fema_nri",
    name: "FEMA National Risk Index",
    owner: "Federal Emergency Management Agency",
    url: "https://www.fema.gov/flood-maps/products-tools/national-risk-index",
    accessPattern: "official_download",
    cadence: "annual",
    risk: "green",
    rights: publicAggregateRights,
    notes: "Use for hazard, exposure, and vulnerability context in grant-ready packs.",
  },
  {
    sourceId: "faa_uas",
    name: "FAA UAS and TFR Data",
    owner: "Federal Aviation Administration",
    url: "https://www.faa.gov/uas",
    accessPattern: "official_api",
    cadence: "event_driven",
    risk: "green",
    rights: publicOfficialRights,
    notes: "Use for drone-readiness constraints, airspace, TFR, LAANC, and public-safety caveats.",
  },
  {
    sourceId: "developer_docs_public",
    name: "Public Developer Documentation",
    owner: "Vendor-specific",
    url: "https://modelcontextprotocol.io/",
    accessPattern: "public_docs",
    cadence: "daily",
    risk: "yellow",
    rights: publicDocsRights,
    notes: "Use for endpoint, SDK, auth-scope, pricing, and changelog diff metadata where terms allow.",
  },
  {
    sourceId: "github_releases",
    name: "GitHub Releases",
    owner: "GitHub and repository maintainers",
    url: "https://docs.github.com/en/rest/releases",
    accessPattern: "official_api",
    cadence: "event_driven",
    risk: "yellow",
    rights: publicDocsRights,
    notes: "Use release metadata and links; respect repository licenses for code/content.",
  },
];

export const products: Product[] = [
  {
    productId: "opportunity_intel_pack",
    title: "Opportunity Intel Pack",
    route: "/v1/artifacts/:id/content",
    method: "GET",
    category: "opportunity_intelligence",
    priceUsd: "0.2500",
    artifactKind: "builder_opportunity_brief",
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    tags: ["x402", "grants", "rfp", "regional", "agent-buyable"],
    sourceIds: ["sam_gov_opportunities", "grants_gov", "regulations_gov", "data_gov_catalog", "census_acs"],
    buyerValue: "Turns fragmented public opportunities into fit-scored, source-cited action packets.",
    disclaimers: ["Not legal advice.", "Not an official agency determination.", "Verify deadlines at the source before filing."],
  },
  {
    productId: "wildfire_regional_intel_pack",
    title: "Regional Wildfire Intelligence Pack",
    route: "/v1/artifacts/:id/content",
    method: "GET",
    category: "regional_wildfire",
    priceUsd: "1.5000",
    artifactKind: "wildfire_readiness_brief",
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    tags: ["wildfire", "regional-intel", "drone-readiness", "public-safety"],
    sourceIds: ["nasa_firms", "nifc_wfigs", "landfire", "nws_alerts", "fema_nri", "faa_uas", "census_acs"],
    buyerValue: "Fuses public fire, fuels, weather, exposure, and airspace data into grant-ready planning output.",
    disclaimers: ["Decision support only.", "Not a replacement for incident command.", "No drone operation is authorized by this report."],
  },
  {
    productId: "cyber_exploited_vuln_priority",
    title: "Exploited Vulnerability Priority Pack",
    route: "/v1/artifacts/:id/content",
    method: "GET",
    category: "defensive_cyber",
    priceUsd: "0.5000",
    artifactKind: "vulnerability_priority_report",
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    tags: ["cyber", "kev", "epss", "nvd", "defensive-only"],
    sourceIds: ["cisa_kev", "nvd_cve", "first_epss", "osv"],
    buyerValue: "Ranks what to fix today using public exploit evidence and defensive remediation context.",
    disclaimers: ["Defensive prioritization only.", "No exploit payloads or credential material.", "Scan only assets you own or are authorized to assess."],
  },
  {
    productId: "market_regime_evidence_pack",
    title: "Market Regime Evidence Pack",
    route: "/v1/artifacts/:id/content",
    method: "GET",
    category: "market_intelligence",
    priceUsd: "1.0000",
    artifactKind: "market_regime_report",
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    tags: ["markets", "macro", "filings", "research-only", "no-execution"],
    sourceIds: ["fred_alfred", "cftc_cot", "sec_edgar", "defillama", "coingecko", "gdelt_2"],
    buyerValue: "Packages macro, positioning, filing, onchain, and narrative signals into non-advisory research artifacts.",
    disclaimers: ["Research and education only.", "Not investment advice.", "No buy/sell/hold recommendations.", "No trade execution."],
  },
  {
    productId: "developer_api_change_radar",
    title: "Developer API Change Radar",
    route: "/v1/artifacts/:id/content",
    method: "GET",
    category: "developer_intelligence",
    priceUsd: "0.2500",
    artifactKind: "api_change_radar",
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    tags: ["developer-docs", "api", "sdk", "agent-builders"],
    sourceIds: ["developer_docs_public", "github_releases"],
    buyerValue: "Flags API, SDK, auth, pricing, and docs changes before agents generate stale code.",
    disclaimers: ["Unofficial derived analysis.", "Verify source docs before production changes.", "No vendor certification implied."],
  },
];

export const artifacts: Artifact[] = [
  {
    artifactId: "aoe_grants_colorado_wildfire_ai",
    productId: "opportunity_intel_pack",
    title: "Colorado Wildfire and AI Workforce Opportunity Brief",
    category: "opportunity_intelligence",
    description: "A source-cited profile for finding grants, public-safety RFPs, and local programs that match wildfire intelligence and workforce training concepts.",
    tags: ["grants", "wildfire", "ai-workforce", "colorado", "public-sector"],
    sourceIds: ["sam_gov_opportunities", "grants_gov", "data_gov_catalog", "census_acs"],
    rights: publicOfficialRights,
    preview: {
      headline: "Find public-sector money for wildfire intelligence without promising hardware before agency trust exists.",
      audience: ["grant_writers", "rural_founders", "fire_district_consultants", "economic_development_groups"],
      dataPoints: ["deadline", "agency", "eligibility", "award_range", "required_documents", "source_vintage"],
      sampleQuestions: ["Which grants fit a regional wildfire intel pilot?", "What evidence is needed before a bid/no-bid decision?"],
      freshness: { class: "daily", ttlSeconds: 86_400, lastVerified: "seeded_static_research_2026-05-08" },
    },
    content: {
      summary: "Use official opportunity portals and public regional datasets to package a bid/no-bid brief for wildfire intelligence, drone-readiness simulation, and rural workforce training. The near-term sale is planning evidence, not drone operations.",
      evidenceCards: [
        {
          title: "Opportunity fit starts with public notices, not bespoke scraping.",
          sourceIds: ["sam_gov_opportunities", "grants_gov"],
          finding: "Federal contract and grant portals expose enough metadata for first-pass eligibility, deadlines, and required-document triage.",
          action: "Build profile inputs for geography, applicant type, capabilities, and target award size before ranking opportunities.",
        },
        {
          title: "Regional context makes the artifact sellable.",
          sourceIds: ["data_gov_catalog", "census_acs"],
          finding: "A grant writer needs county, workforce, exposure, and program-fit context more than another generic opportunity list.",
          action: "Attach source vintage warnings when daily opportunities are mixed with annual Census data.",
        },
      ],
      nextActions: [
        "Create buyer profiles for fire districts, counties, HOAs, utilities, and rural workforce groups.",
        "Add a daily source-refresh job before claiming current opportunity status.",
        "Export the accepted matches to a proposal tracker with source links and deadline proof.",
      ],
      caveats: ["This is not a legal eligibility determination.", "Deadlines and amendments must be verified at the official source before submission."],
      outputPolicy: ["Return derived facts, source links, checklist items, and short attributed snippets only.", "Never resell raw source documents as the product."],
    },
  },
  {
    artifactId: "aoe_wildfire_gunnison_readiness",
    productId: "wildfire_regional_intel_pack",
    title: "Gunnison-Crested Butte Wildfire Readiness Evidence Pack",
    category: "regional_wildfire",
    description: "A regional wildfire intelligence packet blending fire detections, perimeters, fuels, weather, WUI exposure, and drone-readiness constraints.",
    tags: ["wildfire", "gunnison", "wui", "fuels", "drone-readiness"],
    sourceIds: ["nasa_firms", "nifc_wfigs", "landfire", "nws_alerts", "fema_nri", "faa_uas", "census_acs"],
    rights: publicOfficialRights,
    preview: {
      headline: "Sell fire-district intelligence and grant-ready evidence before attempting real drone deployment.",
      audience: ["fire_chiefs", "county_emergency_managers", "utilities", "HOAs", "grant_writers"],
      dataPoints: ["active_fire", "perimeter", "fuels", "weather_alerts", "wui_exposure", "airspace_constraints"],
      sampleQuestions: ["What changed in this AOR in the last 24 hours?", "Can a drone pilot legally and safely fly this mission?"],
      freshness: { class: "hourly", ttlSeconds: 3_600, lastVerified: "seeded_static_research_2026-05-08" },
    },
    content: {
      summary: "The first commercial wildfire product is an intelligence desk: nightly and on-demand evidence packs for risk, readiness, airspace, and simulated coverage. Real drone swarms become an upgrade path after trust, approvals, and procurement constraints are solved.",
      evidenceCards: [
        {
          title: "Live fire context is public but fragmented.",
          sourceIds: ["nasa_firms", "nifc_wfigs", "nws_alerts"],
          finding: "Active detections, incident records, perimeters, and weather alerts live in separate systems with different freshness and confidence.",
          action: "Return a source-health table and explicitly mark stale or missing layers.",
        },
        {
          title: "Drone-readiness is a planning product first.",
          sourceIds: ["faa_uas"],
          finding: "Airspace, TFR, LAANC, public-aircraft, and BVLOS constraints determine whether a sortie is even plausible.",
          action: "Package a no-fly/needs-approval map and SOP checklist before any hardware pitch.",
        },
        {
          title: "Grant evidence needs exposure and mitigation context.",
          sourceIds: ["landfire", "fema_nri", "census_acs"],
          finding: "Fuels, hazard, WUI, demographics, and evacuation constraints turn a map into a fundable mitigation narrative.",
          action: "Create a county-ready appendix with data vintage, methodology, and limitations.",
        },
      ],
      nextActions: [
        "Implement source adapters for FIRMS, NIFC/WFIGS, LANDFIRE metadata, NWS alerts, FEMA NRI, and FAA UAS/TFR links.",
        "Build a sample AOI packet with map-ready GeoJSON and a chief-facing PDF later.",
        "Keep drone operations disabled; model simulated coverage only.",
      ],
      caveats: ["Not incident command.", "Not a flight authorization.", "Not a replacement for local emergency alerts."],
      outputPolicy: ["Use public official data and derived analysis.", "Show uncertainty and source freshness on every map/report."],
    },
  },
  {
    artifactId: "aoe_cyber_kev_epss_priority",
    productId: "cyber_exploited_vuln_priority",
    title: "MSP Exploited Vulnerability Priority Pack",
    category: "defensive_cyber",
    description: "A defensive report that ranks vulnerabilities using CISA KEV, EPSS, NVD, and OSV context without exploit instructions.",
    tags: ["cyber", "msp", "smb", "kev", "epss", "remediation"],
    sourceIds: ["cisa_kev", "nvd_cve", "first_epss", "osv"],
    rights: publicOfficialRights,
    preview: {
      headline: "Tell a small team what to fix today, prove why, and avoid drowning them in CVEs.",
      audience: ["MSPs", "fractional_IT", "SMB_security", "cyber_insurance_support"],
      dataPoints: ["cve", "kev_status", "epss_percentile", "affected_product", "remediation", "proof_links"],
      sampleQuestions: ["Which CVEs from my asset list are known exploited?", "What evidence should go into the client remediation packet?"],
      freshness: { class: "daily", ttlSeconds: 86_400, lastVerified: "seeded_static_research_2026-05-08" },
    },
    content: {
      summary: "The defensible cyber wedge is a paid exploited-vulnerability priority API and human-readable proof packet. It should rank fix-now items using public exploitation evidence and never provide exploit payloads or stolen material.",
      evidenceCards: [
        {
          title: "Known exploitation beats raw severity for urgency.",
          sourceIds: ["cisa_kev", "first_epss"],
          finding: "KEV and EPSS are practical signals for moving from a noisy CVE list to a fix-now queue.",
          action: "Sort by known exploitation, exploit probability, exposure, affected asset criticality, and remediation availability.",
        },
        {
          title: "Package remediation as proof, not panic.",
          sourceIds: ["nvd_cve", "osv"],
          finding: "SMB/MSP buyers need a clear ticket list with version evidence, source links, and remediation notes.",
          action: "Return PDF/JSON-ready findings with no offensive steps or PoC references.",
        },
      ],
      nextActions: [
        "Accept asset inventory exports before any active scanning.",
        "Add customer authorization proof for domain/cloud scans.",
        "Map output to NIST CSF 2.0 and PCI-style evidence packets.",
      ],
      caveats: ["Defensive use only.", "No unauthorized scanning.", "No exploit code.", "No raw credentials or breach dumps."],
      outputPolicy: ["Return metadata, risk ranking, remediation, and citations.", "Suppress exploit instructions and weaponized indicators by default."],
    },
  },
  {
    artifactId: "aoe_macro_regime_public_evidence",
    productId: "market_regime_evidence_pack",
    title: "Macro Regime and Cross-Asset Evidence Pack",
    category: "market_intelligence",
    description: "A non-advisory market-intelligence artifact using macro, positioning, filings, onchain, and narrative sources.",
    tags: ["macro", "markets", "research-only", "filings", "onchain"],
    sourceIds: ["fred_alfred", "cftc_cot", "sec_edgar", "defillama", "coingecko", "gdelt_2"],
    rights: publicOfficialRights,
    preview: {
      headline: "Sell explainable research artifacts, not trading automation or personalized advice.",
      audience: ["research_analysts", "founders", "operators", "agents", "market_research_buyers"],
      dataPoints: ["liquidity", "rates", "inflation", "positioning", "filing_changes", "onchain_flows", "narrative_events"],
      sampleQuestions: ["What changed in the macro regime this week?", "Which filings or flows explain the risk narrative?"],
      freshness: { class: "weekly", ttlSeconds: 604_800, lastVerified: "seeded_static_research_2026-05-08" },
    },
    content: {
      summary: "The safe market wedge is paid research and evidence packs: regime scores, filing-change briefs, onchain market-structure snapshots, and reproducible backtest receipts. The product should avoid personalized advice and all live execution.",
      evidenceCards: [
        {
          title: "Public macro and filings data are strong revenue inputs.",
          sourceIds: ["fred_alfred", "sec_edgar", "cftc_cot"],
          finding: "Macroeconomic series, COT positioning, and EDGAR filings are public, high-demand inputs for research automation.",
          action: "Build repeatable evidence packs with revision dates, methodology, and source links.",
        },
        {
          title: "Onchain data is x402-native but licensing-sensitive.",
          sourceIds: ["defillama", "coingecko"],
          finding: "Agent buyers will pay per snapshot, but raw vendor data redistribution requires source-specific review.",
          action: "Sell derived market-structure analysis and keep raw vendor payloads out of paid responses until licensed.",
        },
      ],
      nextActions: [
        "Build a macro-regime report generator with FRED and CFTC first.",
        "Add SEC filing diff artifacts as a second revenue surface.",
        "Keep backtests reproducible, paper-only, and labeled hypothetical.",
      ],
      caveats: ["Not investment advice.", "No buy/sell/hold recommendations.", "No trade execution.", "Data may be delayed or incomplete."],
      outputPolicy: ["Return research context and reproducible assumptions.", "Do not personalize recommendations to a buyer portfolio."],
    },
  },
  {
    artifactId: "aoe_x402_api_change_radar",
    productId: "developer_api_change_radar",
    title: "x402 and Agent Payments API Change Radar",
    category: "developer_intelligence",
    description: "A public-docs change radar for x402, MCP, and agent-payment infrastructure.",
    tags: ["x402", "mcp", "developer-docs", "api-change", "agent-payments"],
    sourceIds: ["developer_docs_public", "github_releases"],
    rights: publicDocsRights,
    preview: {
      headline: "Reduce stale agent code by selling tested, source-cited API change summaries.",
      audience: ["agent_builders", "devrel", "developer_tooling_founders", "technical_consultants"],
      dataPoints: ["endpoint", "sdk_version", "network_support", "auth_scope", "pricing_change", "breaking_change"],
      sampleQuestions: ["Which x402 SDK examples changed this week?", "Which docs are tested versus untested?"],
      freshness: { class: "daily", ttlSeconds: 86_400, lastVerified: "seeded_static_research_2026-05-08" },
    },
    content: {
      summary: "Developer API-change radar is a clean demo vertical: public docs and releases become a paid diff, test-status, and migration-impact artifact for agents before they generate code.",
      evidenceCards: [
        {
          title: "Docs are source material, not a license-free training corpus.",
          sourceIds: ["developer_docs_public"],
          finding: "The safe output is a short sourced diff and tested contract note, not a copy of the docs.",
          action: "Track endpoint names, auth scopes, package versions, and source links with a source-rights envelope.",
        },
        {
          title: "Release metadata creates objective freshness.",
          sourceIds: ["github_releases"],
          finding: "Release tags and changelogs are useful machine-readable triggers for docs and SDK monitors.",
          action: "Store release ids, timestamps, hashes, and test status for every derived radar item.",
        },
      ],
      nextActions: [
        "Add a docs-diff worker for x402, MCP, Hono, and Cloudflare Agents docs.",
        "Mark every snippet tested, untested, stale, or auth-blocked.",
        "Expose an MCP search/quote/fetch flow after the REST kernel stabilizes.",
      ],
      caveats: ["Unofficial derived analysis.", "No vendor certification.", "Verify source docs before production changes."],
      outputPolicy: ["Return metadata, links, and short attributed summaries.", "Do not republish full docs or gated content."],
    },
  },
];

export function getProduct(productId: string): Product | undefined {
  return products.find((product) => product.productId === productId);
}

export function getArtifact(artifactId: string): Artifact | undefined {
  return artifacts.find((artifact) => artifact.artifactId === artifactId);
}

export function getSource(sourceId: string): SourceRecord | undefined {
  return sources.find((source) => source.sourceId === sourceId);
}
