import { shortHash, sha256 } from "./hash.js";
import type { Artifact, Quote, Receipt, ReceiptSettlement } from "./types.js";
import { getProduct } from "./catalog.js";
import { getX402PaymentStatus, simulatedPayTo } from "./x402-config.js";

export function buildQuote(artifact: Artifact, now = new Date()): Quote {
  const product = getProduct(artifact.productId);
  if (!product) {
    throw new Error(`Product not found for artifact ${artifact.artifactId}`);
  }

  const quoteDate = now.toISOString().slice(0, 10);
  const quoteSeed = {
    artifactId: artifact.artifactId,
    productId: product.productId,
    priceUsd: product.priceUsd,
    quoteDate,
    mode: product.settlementMode,
  };
  const quoteId = `quote_${shortHash(quoteSeed, 18)}`;
  const workOrderId = `wo_${shortHash({ quoteId, artifactHash: sha256(artifact.content) }, 18)}`;
  const expiresAt = new Date(now.getTime() + 15 * 60 * 1000).toISOString();
  const paymentStatus = getX402PaymentStatus();
  const payTo = paymentStatus.ready && paymentStatus.payTo.address ? paymentStatus.payTo.address : simulatedPayTo();

  return {
    quoteId,
    workOrderId,
    artifactId: artifact.artifactId,
    productId: product.productId,
    priceUsd: product.priceUsd,
    currency: "USDC",
    paymentProtocol: "x402",
    settlementMode: product.settlementMode,
    liveSettlementAllowed: false,
    expiresAt,
    accepted: [
      {
        scheme: "exact",
        network: paymentStatus.network.id,
        asset: "USDC",
        amountUsd: product.priceUsd,
        payTo,
      },
    ],
    rights: artifact.rights,
    sourceIds: artifact.sourceIds,
  };
}

export function expectedSimulatedPayment(workOrderId: string): string {
  return `simulated:${workOrderId}`;
}

export function hasValidSimulatedPayment(headers: Headers, quote: Quote): boolean {
  const payment = headers.get("x-aoe-payment") ?? headers.get("payment-signature") ?? "";
  return payment.trim() === expectedSimulatedPayment(quote.workOrderId);
}

export function paymentRequiredPayload(quote: Quote, options: { officialX402Testnet?: boolean; configErrors?: string[] } = {}): Record<string, unknown> {
  const paymentStatus = getX402PaymentStatus();
  const instructions = options.officialX402Testnet
    ? [
        "x402 testnet only: use a burner wallet funded with Base Sepolia test USDC.",
        "Retry with the official PAYMENT-SIGNATURE header generated by @x402/fetch or @x402/core/client.",
        "Do not send mainnet funds; liveSettlementAllowed is false and only eip155:84532 is accepted.",
      ]
    : [
        "Local demo only: do not send funds to the simulated payTo address.",
        `Retry with header X-AOE-Payment: ${expectedSimulatedPayment(quote.workOrderId)}`,
        "Set AOE_PAYMENT_MODE=x402_testnet plus AOE_X402_PAY_TO to test the official @x402 Hono middleware on Base Sepolia.",
      ];

  return {
    error: "payment_required",
    protocol: "x402",
    mode: paymentStatus.mode,
    activeRail: paymentStatus.activeRail,
    liveSettlementAllowed: false,
    workOrderId: quote.workOrderId,
    quote,
    ...(options.configErrors?.length ? { configErrors: options.configErrors } : {}),
    instructions,
  };
}

export function paymentRequiredHeader(quote: Quote): string {
  return Buffer.from(JSON.stringify(paymentRequiredPayload(quote))).toString("base64url");
}

export function buildReceipt(artifact: Artifact, quote: Quote, now = new Date(), settlement?: ReceiptSettlement): Receipt {
  const defaultSettlement: ReceiptSettlement = {
    rail: "simulated_header",
    status: "simulated",
    network: quote.accepted[0]?.network ?? "eip155:84532",
    asset: "USDC",
    amount: quote.priceUsd,
    liveSettlementAllowed: false,
  };

  return {
    receiptId: `rcpt_${shortHash({ quoteId: quote.quoteId, paidAt: now.toISOString() }, 18)}`,
    quoteId: quote.quoteId,
    workOrderId: quote.workOrderId,
    artifactId: artifact.artifactId,
    productId: artifact.productId,
    settlementMode: "simulated_or_testnet",
    liveSettlementAllowed: false,
    paidAt: now.toISOString(),
    artifactHash: sha256(artifact.content),
    sourceIds: artifact.sourceIds,
    rights: artifact.rights,
    settlement: settlement ?? defaultSettlement,
  };
}
