import { productRoutes, products } from "./catalog.js";
import { buildCyberExpertEvalReport } from "./adapters/cyber-evals.js";
import { resolveCyberModelProvider } from "./adapters/cyber-model-provider.js";
import { getTelegramBotToken } from "./telegram.js";

export interface AdapterReadiness {
  adapterId: string;
  productId: string | null;
  workstreamId?: string;
  x402Stream: boolean;
  sourceIds: string[];
  status: "live_read_only" | "configured_stub" | "key_required" | "blocked";
  endpoint: string | null;
  inputMode: string;
  sideEffects:
    | "none"
    | "public_cve_source_fetch_only"
    | "public_chain_receipt_fetch_only"
    | "local_model_inference_only"
    | "deterministic_analysis_plus_optional_public_fetch_and_optional_local_inference";
  liveSettlementAllowed: false;
  notes: string[];
}

export function buildReadiness() {
  const cyberEvalSuiteHash = buildCyberExpertEvalReport().evidenceProof.evalSuiteHash;
  const cyberModelProvider = resolveCyberModelProvider(process.env, cyberEvalSuiteHash);
  const adapters: AdapterReadiness[] = [
    {
      adapterId: "cyber_vuln_priority",
      productId: "cyber_exploited_vuln_priority",
      x402Stream: true,
      sourceIds: ["cisa_kev", "first_epss", "nvd_cve"],
      status: "live_read_only",
      endpoint: "/v1/adapters/cyber/vuln-priority/preview",
      inputMode: "CVE list, CSV inventory, or nested JSON inventory via CLI/API",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["No active scanning.", "No exploit payloads.", "No credential material."],
    },
    {
      adapterId: "cyber_inventory_priority",
      productId: "cyber_exploited_vuln_priority",
      x402Stream: true,
      sourceIds: ["cisa_kev", "first_epss", "nvd_cve"],
      status: "live_read_only",
      endpoint: "/v1/adapters/cyber/inventory-priority/preview",
      inputMode: "Authorized JSON inventory with CVEs, assets, or asset rows",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["No active scanning.", "No exploit payloads.", "Buyer inventory evidence only."],
    },
    {
      adapterId: "cyber_expert_harness_blueprint",
      productId: "cyber_expert_harness_blueprint",
      x402Stream: true,
      sourceIds: [
        "microsoft_mdash_blog",
        "microsoft_agent_defense_in_depth",
        "microsoft_security_copilot_docs",
        "cybergym_benchmark",
        "oss_crs",
        "team_atlanta_atlantis",
        "anthropic_mythos_public",
        "trm_sanctions_docs",
        "ofac_sanctions_lists",
      ],
      status: "live_read_only",
      endpoint: "/v1/streams/cyber-expert-harness/blueprint",
      inputMode: "Optional focus and runtime toggles; returns a defensive agentic architecture blueprint",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: [
        "No active scanning.",
        "No exploit payload generation.",
        "Blueprint for local GPU, RAG, fine-tuning, proof, and compliance lanes only.",
      ],
    },
    {
      adapterId: "cyber_expert_case_store",
      productId: "cyber_expert_case_store_pack",
      x402Stream: true,
      sourceIds: [
        "buyer_authorized_inventory",
        "cisa_kev",
        "nvd_cve",
        "first_epss",
        "osv",
        "crypto_incident_public_metadata",
        "defillama",
        "trm_sanctions_docs",
        "ofac_sanctions_lists",
      ],
      status: "live_read_only",
      endpoint: "/v1/streams/cyber-expert/case-store",
      inputMode: "Authorized inventory, CVEs, crypto incident metadata, proof commitments, and private note hashes",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: [
        "No active scanning.",
        "No live source calls.",
        "No exploit payloads.",
        "No raw private inventory, wallet addresses, secrets, notes, or vendor payloads are echoed.",
      ],
    },
    {
      adapterId: "cyber_expert_model_preview",
      productId: "cyber_expert_model_preview_pack",
      x402Stream: true,
      sourceIds: [
        "buyer_authorized_inventory",
        "cisa_kev",
        "nvd_cve",
        "first_epss",
        "osv",
        "crypto_incident_public_metadata",
        "defillama",
        "trm_sanctions_docs",
        "ofac_sanctions_lists",
      ],
      status: "live_read_only",
      endpoint: "/v1/streams/cyber-expert/model-preview",
      inputMode: "Same payload as case-store route; current provider is rules-only with zero model calls",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: [
        "No model provider calls.",
        "No local GPU use.",
        "No paid API calls.",
        "No active scanning or exploit payloads.",
        "No raw private inventory, wallet addresses, secrets, notes, or vendor payloads are echoed.",
      ],
    },
    {
      adapterId: "cyber_expert_case_brief",
      productId: "cyber_expert_model_preview_pack",
      x402Stream: true,
      sourceIds: [
        "buyer_authorized_inventory",
        "cisa_kev",
        "nvd_cve",
        "first_epss",
        "osv",
        "crypto_incident_public_metadata",
        "defillama",
        "trm_sanctions_docs",
        "ofac_sanctions_lists",
      ],
      status: "live_read_only",
      endpoint: "/v1/streams/cyber-expert/case-brief",
      inputMode: "Same payload as case-store route plus optional public CVE refresh and optional local model advisory",
      sideEffects: "deterministic_analysis_plus_optional_public_fetch_and_optional_local_inference",
      liveSettlementAllowed: false,
      notes: [
        "Preferred operator-facing brief.",
        "Public refresh sends CVE identifiers only.",
        "Local model call is optional, hash-gated, and non-authoritative.",
        "No active scanning, exploit payloads, Telegram sends, proof posts, trading, or money movement.",
      ],
    },
    {
      adapterId: "cyber_expert_case_brief_report",
      productId: "cyber_expert_model_preview_pack",
      x402Stream: true,
      sourceIds: [
        "buyer_authorized_inventory",
        "cisa_kev",
        "nvd_cve",
        "first_epss",
        "osv",
        "crypto_incident_public_metadata",
        "defillama",
        "trm_sanctions_docs",
        "ofac_sanctions_lists",
      ],
      status: "live_read_only",
      endpoint: "/v1/streams/cyber-expert/case-brief/report",
      inputMode: "Same payload as case-brief route; returns escaped buyer-safe HTML inside a JSON contract",
      sideEffects: "deterministic_analysis_plus_optional_public_fetch_and_optional_local_inference",
      liveSettlementAllowed: false,
      notes: [
        "Derived HTML report only.",
        "Dynamic content is escaped.",
        "Public source refresh sends CVE identifiers only.",
        "Local model output is optional, hash-gated, and non-authoritative.",
        "No active scanning, exploit payloads, Telegram sends, proof posts, trading, or money movement.",
      ],
    },
    {
      adapterId: "cyber_public_cve_refresh",
      productId: "cyber_expert_model_preview_pack",
      x402Stream: false,
      sourceIds: ["cisa_kev", "first_epss", "nvd_cve", "osv"],
      status: "live_read_only",
      endpoint: "/v1/streams/cyber-expert/public-cve-refresh",
      inputMode: "CVE identifiers only; fetches public KEV, EPSS, NVD, and OSV freshness",
      sideEffects: "public_cve_source_fetch_only",
      liveSettlementAllowed: false,
      notes: [
        "No buyer inventory or hostnames sent to public sources.",
        "KEV, EPSS, NVD, and OSV are prioritization evidence only.",
        "No active scanning or exploit payloads.",
      ],
    },
    {
      adapterId: "compliance_decision_preview",
      productId: "cyber_expert_case_store_pack",
      x402Stream: true,
      sourceIds: ["ofac_sanctions_lists", "trm_sanctions_docs"],
      status: "live_read_only",
      endpoint: "/v1/compliance/screening/decision-preview",
      inputMode: "Commitment, policy version, optional Merkle root, expiry, and decision; raw wallet addresses rejected",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: [
        "Commitment-only preview.",
        "No live TRM or OFAC screening call.",
        "No raw wallet addresses or vendor payloads accepted.",
        "No on-chain proof is posted.",
        "Not sanctions clearance.",
      ],
    },
    {
      adapterId: "zero_g_proof_readiness",
      productId: "zero_g_hackathon_proof_pack",
      x402Stream: true,
      sourceIds: ["zero_g_chain_public_rpc", "zero_guard_hackathon_public_proof", "ofac_sanctions_lists", "trm_sanctions_docs"],
      status: "live_read_only",
      endpoint: "/v1/hackathon/0g-proof",
      inputMode: "No input; reads a public 0G anchor receipt and returns proof-readiness metadata",
      sideEffects: "public_chain_receipt_fetch_only",
      liveSettlementAllowed: false,
      notes: [
        "Read-only eth_getTransactionReceipt for an existing public 0guard anchor transaction.",
        "No wallet signing, transaction broadcast, proof posting, 0G node start, live settlement, or private compliance screening.",
        "Designed as the judge-facing 0G proof surface for AOE while 0guard remains the specialized proof demo.",
      ],
    },
    {
      adapterId: "cyber_ollama_model_preview",
      productId: "cyber_expert_model_preview_pack",
      x402Stream: true,
      sourceIds: ["buyer_authorized_inventory", "cisa_kev", "first_epss", "nvd_cve", "osv"],
      status: cyberModelProvider.status === "ready_windows_ollama_capped_worker" ? "configured_stub" : "key_required",
      endpoint: "/v1/streams/cyber-expert/windows-ollama/preview",
      inputMode: "Same payload as case-store route; requires Windows/Ollama env gates and current eval-suite hash",
      sideEffects: "local_model_inference_only",
      liveSettlementAllowed: false,
      notes: [
        `Provider gate status: ${cyberModelProvider.status}.`,
        "Gate-ready means configured but unprobed; use /windows-ollama/status before calling the preview route.",
        "Calls /api/tags then at most one /api/chat only when every gate is present.",
        "Route-level simulated x402 access is required before local model inference is attempted.",
        "No /api/generate, embeddings, pull, delete, create, copy, show, or ps calls.",
        "Raw prompt, raw output, endpoint URL, and model name are not echoed.",
      ],
    },
    {
      adapterId: "cyber_expert_eval_report",
      productId: "cyber_expert_model_preview_pack",
      x402Stream: false,
      sourceIds: [],
      status: "live_read_only",
      endpoint: "/v1/streams/cyber-expert/evals",
      inputMode: "No input; runs deterministic eval fixtures against the model-preview contract",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["No model provider calls.", "No local GPU use.", "No paid API calls.", "No active scanning or exploit payloads."],
    },
    {
      adapterId: "cyber_expert_provider_status",
      productId: "cyber_expert_model_preview_pack",
      x402Stream: false,
      sourceIds: [],
      status: "live_read_only",
      endpoint: "/v1/streams/cyber-expert/provider-status",
      inputMode: "No input; reports provider gate status without environment values",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["No env values echoed.", "No model provider calls.", "No local GPU use.", "No paid API calls."],
    },
    {
      adapterId: "cyber_windows_ollama_status",
      productId: "cyber_expert_model_preview_pack",
      x402Stream: false,
      sourceIds: [],
      status: process.env.AOE_WINDOWS_OLLAMA_URL ? "live_read_only" : "key_required",
      endpoint: "/v1/streams/cyber-expert/windows-ollama/status",
      inputMode: "No input; reads /api/tags from configured AOE_WINDOWS_OLLAMA_URL only",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: [
        "Requires AOE_WINDOWS_OLLAMA_URL for live readback.",
        "No endpoint URL or model names echoed.",
        "No /api/chat, /api/generate, or embeddings calls.",
        "No local GPU work requested.",
      ],
    },
    {
      adapterId: "wildfire_nws_alerts",
      productId: null,
      workstreamId: "wildfire_drone_readiness_lane",
      x402Stream: false,
      sourceIds: ["nws_alerts"],
      status: "live_read_only",
      endpoint: "/v1/adapters/wildfire/alerts/preview",
      inputMode: "State area code or lat/lon point",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["Not incident command.", "No alert sends.", "No drone authorization."],
    },
    {
      adapterId: "wildfire_wfigs_perimeters",
      productId: null,
      workstreamId: "wildfire_drone_readiness_lane",
      x402Stream: false,
      sourceIds: ["nifc_wfigs"],
      status: "live_read_only",
      endpoint: "/v1/adapters/wildfire/wfigs-perimeters/preview",
      inputMode: "Optional state code plus result limit",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["Public NIFC/WFIGS ArcGIS service.", "Perimeters are not available for every incident.", "Not evacuation authority."],
    },
    {
      adapterId: "market_live_upstream_proof",
      productId: "market_regime_evidence_pack",
      x402Stream: true,
      sourceIds: ["sec_edgar", "fred_alfred"],
      status: "live_read_only",
      endpoint: "/v1/streams/market-context/live-proof",
      inputMode: "Ticker plus optional FRED series ids; real upstream probe only",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: [
        "Proves current SEC/FRED source availability and evidence hashes.",
        "No mock data in the route response.",
        "No investment advice, payment settlement, or trade execution.",
      ],
    },
    {
      adapterId: "market_sec_macro_context",
      productId: "market_regime_evidence_pack",
      x402Stream: true,
      sourceIds: ["sec_edgar", "fred_alfred"],
      status: "live_read_only",
      endpoint: "/v1/streams/market-context/preview",
      inputMode: "Ticker plus optional FRED series ids",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["Featured storefront stream.", "SEC filings plus macro context.", "No investment advice or trade execution."],
    },
    {
      adapterId: "markets_sec_filings",
      productId: "market_regime_evidence_pack",
      x402Stream: true,
      sourceIds: ["sec_edgar"],
      status: "live_read_only",
      endpoint: "/v1/adapters/markets/sec-filings/preview",
      inputMode: "Ticker or CIK plus optional form filters",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["Document intelligence only.", "No investment advice.", "No trade execution."],
    },
    {
      adapterId: "markets_fred_series",
      productId: "market_regime_evidence_pack",
      x402Stream: true,
      sourceIds: ["fred_alfred"],
      status: "live_read_only",
      endpoint: "/v1/adapters/markets/fred-series/preview",
      inputMode: "FRED series ids",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["Public graph CSV preview.", "Use ALFRED vintages for production revision-aware research.", "No trading signal."],
    },
    {
      adapterId: "bankless_mcp_manifest",
      productId: "crypto_research_thesis_pack",
      x402Stream: true,
      sourceIds: ["bankless_onchain_mcp"],
      status: "live_read_only",
      endpoint: "/v1/mcp/bankless/manifest",
      inputMode: "No input; reports optional user-configured MCP status",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["Requires user-owned Bankless API token for live MCP calls.", "AOE does not store or echo token values.", "No wallet signing or money movement."],
    },
    {
      adapterId: "bankless_podcast_recent",
      productId: "crypto_research_thesis_pack",
      x402Stream: true,
      sourceIds: ["bankless_podcast_rss"],
      status: "live_read_only",
      endpoint: "/v1/adapters/bankless/podcast/recent",
      inputMode: "Optional keyword query and result limit",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["Public RSS metadata only.", "No audio download.", "No full transcript resale."],
    },
    {
      adapterId: "defi_report_public_inventory",
      productId: "crypto_research_thesis_pack",
      x402Stream: true,
      sourceIds: ["the_defi_report_public_metadata"],
      status: "live_read_only",
      endpoint: "/v1/research/defi-report/inventory",
      inputMode: "No input; public metadata inventory",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["No article-body scraping.", "No paywall or anti-bot bypass.", "Methodology tags and source links only."],
    },
    {
      adapterId: "crypto_thesis_preview",
      productId: "crypto_research_thesis_pack",
      x402Stream: true,
      sourceIds: ["bankless_podcast_rss", "bankless_onchain_mcp", "the_defi_report_public_metadata", "coingecko", "defillama"],
      status: "live_read_only",
      endpoint: "/v1/streams/crypto-thesis/preview",
      inputMode: "Asset symbol, CoinGecko id, optional DeFiLlama slug, optional Bankless query",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["Non-advisory research only.", "No buy/sell/hold or price targets.", "No trade execution or settlement."],
    },
    {
      adapterId: "telegram_mini_app_registration",
      productId: null,
      workstreamId: "telegram_mini_app_opt_in",
      x402Stream: false,
      sourceIds: ["telegram_mini_apps_docs"],
      status: getTelegramBotToken() ? "configured_stub" : "key_required",
      endpoint: "/v1/telegram/register",
      inputMode: "Telegram Mini App initData plus explicit opt-in consent",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: [
        "Verifies Telegram initData before registration.",
        "No Telegram sends or webhook registration.",
        "Persistent opt-in storage is intentionally disabled in the demo slice.",
      ],
    },
    {
      adapterId: "wildfire_nasa_firms",
      productId: null,
      workstreamId: "wildfire_drone_readiness_lane",
      x402Stream: false,
      sourceIds: ["nasa_firms"],
      status: process.env.NASA_FIRMS_MAP_KEY ? "configured_stub" : "key_required",
      endpoint: null,
      inputMode: "Future AOI bounding box or country query",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: ["NASA FIRMS MAP_KEY required.", "No drone operation.", "Use as detection evidence, not evacuation authority."],
    },
    {
      adapterId: "opportunity_public_programs",
      productId: "opportunity_intel_pack",
      x402Stream: true,
      sourceIds: ["sam_gov_opportunities", "grants_gov", "regulations_gov", "data_gov_catalog"],
      status: "live_read_only",
      endpoint: "/v1/adapters/opportunities/public-programs/preview",
      inputMode: "Keyword, optional agency hints, and result limit",
      sideEffects: "none",
      liveSettlementAllowed: false,
      notes: [
        "Uses unauthenticated Grants.gov search and Data.gov Catalog metadata.",
        "SAM.gov opportunities remain key-required and are reported without being called.",
        "Do not scrape authenticated portals or resell raw opportunity packages.",
      ],
    },
  ];

  const missingProductSchemaIds = products.filter((product) => !product.schemaId).map((product) => product.productId);
  const missingProductQuality = products
    .filter(
      (product) =>
        product.quality.buyerValueMetrics.length === 0 ||
        product.quality.sourceFreshnessSla.caveats.length === 0 ||
        product.quality.auditSignals.length === 0,
    )
    .map((product) => product.productId);
  const missingRouteSchemaIds = productRoutes.filter((route) => !route.schemaId).map((route) => route.routeId);
  const paidContentRoutes = productRoutes.filter((route) => route.access === "simulated_x402_payment");
  const publicDiscoveryRoutes = productRoutes.filter((route) => route.access === "public");

  return {
    schemaId: "aoe.readiness.v1",
    generatedAt: new Date().toISOString(),
    liveSettlementAllowed: false,
    externalSideEffectsAllowed: false,
    adapters,
    contracts: {
      schemaId: "aoe.readiness.contracts.v1",
      buyerDiscoveryReady: missingProductSchemaIds.length === 0 && missingProductQuality.length === 0 && missingRouteSchemaIds.length === 0,
      products: {
        count: products.length,
        schemaIds: products.map((product) => product.schemaId),
        missingSchemaIds: missingProductSchemaIds,
        missingQualityMetadata: missingProductQuality,
      },
      routes: {
        discoveryEndpoint: "/v1/routes",
        count: productRoutes.length,
        publicCount: publicDiscoveryRoutes.length,
        simulatedPaymentRequiredCount: paidContentRoutes.length,
        missingSchemaIds: missingRouteSchemaIds,
        paidContentRouteIds: paidContentRoutes.map((route) => route.routeId),
      },
    },
    counts: adapters.reduce(
      (acc, adapter) => {
        acc[adapter.status] += 1;
        return acc;
      },
      { live_read_only: 0, configured_stub: 0, key_required: 0, blocked: 0 } satisfies Record<AdapterReadiness["status"], number>,
    ),
  };
}
